### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by n00bslayr94** [platz1de/Waterlogging#4]
[Mon_Apr_8-16.13.48-BST_2024.log](https://github.com/platz1de/Waterlogging/files/14907494/Mon_Apr_8-16.13.48-BST_2024.log)

**Comment by platz1de** [comment]
The issue is probably produced by a different plugin which schedules block updates in unloaded chunks
This plugin does not influence the flow of normal water (it only appears in the stack trace)
